language: rust

rust:
    - nightly

notifications:
    email:
        on_success: never
        on_failure: always

sudo: false

addons:
    apt:
        packages:
            - nasm
            - qemu-system-x86

install:
    - ./downloadrustlibdir.sh nightly

script:
    - make
    - "{ sleep 10; echo q; } | qemu-system-i386 -kernel bin/kernel.bin -monitor stdio -display none"
