language: rust

rust:
    - nightly

notifications:
    email:
        on_success: never
        on_failure: always

sudo: false

addons:
    apt:
        packages:
            - nasm
            - qemu-kvm

install:
    - rustup target add i686-unknown-linux-gnu

script:
    - make
    - "{ sleep 10; echo q; } | qemu-system-x86_64 -kernel bin/kernel.bin -monitor stdio -display none"
